name: Tag and Publish
on:
  workflow_dispatch:
    inputs:
      version:
        description: New version
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  publish:
    name: Create new version ${{ github.event.inputs.version }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      - name: Generate new version
        run: npm version ${{ github.event.inputs.version }}

      - name: Push new version tag to repository
        run: git push origin main --tags

      - name: Build
        run: npm i && npm run build

      - name: Set NPM_TOKEN
        run: npm config set "//registry.npmjs.org/:_authToken"=${{ secrets.NPM_TOKEN }}

      - name: Publish
        run: npm publish --access=public